version: '3.7'
services:

  redpanda:
    # NOTE: Use the latest version here!
    image: docker.redpanda.com/vectorized/redpanda:latest
    container_name: redpanda-1
    command:
    - redpanda
    - start
    - --smp
    - '1'
    - --reserve-memory
    - 0M
    - --overprovisioned
    - --set redpanda.auto_create_topics_enabled=true 
    - --set redpanda.empty_seed_starts_cluster=false
    - --seeds "redpanda-1:33145"
    - --kafka-addr
    - PLAINTEXT://0.0.0.0:29092,OUTSIDE://0.0.0.0:9092
    - --advertise-kafka-addr
    - PLAINTEXT://redpanda:29092,OUTSIDE://localhost:9092
    - --pandaproxy-addr
    - PLAINTEXT://0.0.0.0:28082,OUTSIDE://0.0.0.0:8082
    - --advertise-pandaproxy-addr
    - PLAINTEXT://redpanda:28082,OUTSIDE://localhost:8082
    - --advertise-rpc-addr redpanda-1:33145
    ports:
    - 8081:8081
    - 8082:8082
    - 9092:9092
    - 28082:28082
    - 29092:29092

  console:
    image: docker.redpanda.com/vectorized/console:latest
    restart: on-failure
    entrypoint: /bin/sh
    command: -c "echo \"$$CONSOLE_CONFIG_FILE\" > /tmp/config.yml; /app/console"
    environment:
      CONFIG_FILEPATH: /tmp/config.yml
      CONSOLE_CONFIG_FILE: |
        kafka:
          brokers: ["redpanda:29092"]
          schemaRegistry:
            enabled: true
            urls: ["http://redpanda:8081"]
    ports:
      - "9090:8080"
    depends_on:
      - redpanda

  kafka-provisioning:
    image: docker.redpanda.com/vectorized/redpanda:latest
    restart: "no"
    entrypoint: ["/bin/sh","-c"]
    command:
    - |
        echo "wait 5 second for redpanda to get ready"
        sleep 5
        rpk topic create hotconfig.schema.json.v1 -c cleanup.policy=compact --brokers redpanda:29092
        rpk topic create hotconfig.data.json.v1 -c cleanup.policy=compact --brokers redpanda:29092
    depends_on:
      - redpanda